### PR TITLE
Use gcr instead of dockerhub in Benchmarking wdl

### PR DESCRIPTION
**Pull request by meganshand**
I was getting timeout errors from pulling the gatk docker from dockerhub. Using google instead should fix that.

### CODE REVIEW

**Comment by kachulis** [comment]
👍  yeah the dockerhub throttling strikes again.  Should we move all the dockers over to gcr?  I imagine this will affect anything that scattered any significant number of times...

**Comment by meganshand** [comment]
eh, I wouldn't worry until it becomes an issue. It's always easy to switch over later, it's just especially nice that gatk already exists on gcr.

**Comment by meganshand** [comment]
Oh @kachulis could you please officially approve? Github won't let me merge without an "approving review"

**Comment by kachulis** [comment]
sounds good!

**Review by kachulis — APPROVED** [review]

**Pull request merged**
