### PR TITLE
Fixed error in CreateAggregationSets when reading booleans as strings

### PR DESCRIPTION
**Pull request by michaelgatzen**
- Also skipping blank samples when creating aggregation sets

### CODE REVIEW

**Comment by michaelgatzen** [comment]
A fix is being worked on on the submission/Terra side, we should still consider merging this as other booleans might not be read incorrectly (such as `delivered`)

**Comment by kachulis** [comment]
Thanks @michaelgatzen, this looks good to me.  Just rerunning the tests to see if the failure goes away, and then will approve and merge.  I also want to add the same fix to ManualQCPRS, but I can do that once this gets merged.

**Comment by michaelgatzen** [comment]
@kachulis The [4bff4e2](https://github.com/broadinstitute/palantir-workflows/pull/171/commits/4bff4e2a3e7f2dfe361ce17d93d44befd686dbd4) commit looks good!

**Review by kachulis — APPROVED** [review]
Alright, looks like the test failures are due to some unrelated docker version deprecation nonsense (see #172).  So I am comfortable merging this with that test failing.  

@michaelgatzen can you just take a look at the additional changes I made to CreateAggregationSets and approve as well before I merge this?

**Pull request merged**
